feat:메인페이지 만들고 컴퍼넌트 몇개 만들었습니다.
YullinDeveloper/yullin-wiki-frontend pull request #4
Opened 2024-03-10 10:11 UTC by kebab000

2024-03-22 07:33 UTC, alicehrk requested changes
전체적으로 수고 많으셨습니다!! 짜잘한 것만 수정하면 될 것 같아요 :D

2024-03-22 07:33 UTC, alicehrk commented on src/components/Footer/Footer.js
footer는 아직 안만든 상황인거죠?? 여전히 className 방식을 쓰고 있길래 물어봅니당!

2024-03-22 07:33 UTC, alicehrk commented on src/components/MainCardWrapper/MainCardWrapper.js
> +        desc={
desc라는 이름도 좋지만, 개인적으로는 어떤 의민지 바로 와닿지 않는 것 같아요..! content와 같은 변수명을 사용해보는건 어떨까요? 😮

2024-03-22 07:33 UTC, alicehrk commented on src/components/MediumCard/style.js
> +  font-family: 'Pretendard';
피그마 상에서 이 부분만 font-family가 다른가요?? 그렇지 않다면 전역적으로 font-family를 설정해뒀으니 각 컴포넌트에서 중복해서 선언할 필요는 없을 것 같아요!

2024-03-22 07:33 UTC, alicehrk commented on src/components/MediumCard/style.js
> +  letter-spacing: 0px;
요런 기본값들도 명시적으로 표현할 이유가 없다면 생략해도 좋을 것 같습니다!

2024-03-22 07:33 UTC, alicehrk commented on src/components/SmallCard/SmallCard.css
이 파일은 이제 사용하지 않는 거라면 지웁시다!

2024-03-22 07:33 UTC, alicehrk commented on src/pages/Main/main.css
main.css만 styled-components로 수정하면 될 것 같네요!

2024-03-24 12:05 UTC, kebab000 commented on src/components/Footer/Footer.js
넹 아직 작업 안들어 갔습니다.

2024-03-26 11:22 UTC, kebab000 commented on src/components/SmallCard/SmallCard.css
이건 만들어야 되는데 파일만 만들어두고 아직 작업을 못했습니다.

2024-08-20 02:28 UTC, merged