add: LargeCard 컴포넌트 생성
YullinDeveloper/yullin-wiki-frontend pull request #5
Opened 2024-03-10 10:11 UTC by RyuChaewon

2024-03-23 10:37 UTC, alicehrk requested changes
처음하는데도 너무너무 잘했어요!!!🥰 고생했어요❤️

2024-03-23 10:37 UTC, alicehrk commented on src/components/Category/style.js
> +  font-family: Pretendard;
font-family는 대체적으로 한 프로젝트에서 통일되어 있기 때문에, 전체 설정에서 한번만 설정하면 돼요! 각 컴포넌트에 따로 설정해주지 않아도 됩니당

2024-03-23 10:37 UTC, alicehrk commented on src/components/Category/style.js
> +  text-align: left;
`letter-spacing: 0px`이나 `text-align: left`같은 스타일들은 기본값입니다! 따라서 생략해도 좋을 것 같아요 :)

2024-03-23 10:37 UTC, alicehrk commented on src/components/CommentCount/style.js
이 디자인 구현하느라 고생 많았어요..🥲 이렇게 하나하나 css로 구현해도 좋지만, 이런 복잡한 icon의 경우 그냥 이미지로 받아와서 사용하는 편이 훨씬 편할거에요!

2024-03-23 10:37 UTC, alicehrk commented on src/components/LargeCard/LargeCard.css
시간 날 때 styled-components를 사용하는 형식으로 바꿔주세용!

2024-03-25 04:09 UTC, RyuChaewon commented
앗 커밋 메시지 실수... 아무튼 리뷰 바탕으로 수정 해보았습니다..!

2024-08-21 11:18 UTC, merged